navbar
healthier-ai/healthier-ai.github.io pull request #4
Opened 2020-04-24 10:42 UTC by Yagna24

Added the files.

2020-04-24 13:36 UTC, arps18 requested changes
The HTML and CSS file are not working correctly, kindly look into the issue!

2020-04-27 14:02 UTC, arps18 requested changes

2020-04-27 14:02 UTC, arps18 commented on navbar/index.html
> +<link rel = "stylesheet"  href = "/home/yagna/Desktop/proj/healthier-ai.github.io-master/navbar/index.css" type="text/css">
Set proper Path!

2020-04-27 14:02 UTC, arps18 commented on navbar/index.html
> +<style>
Separate CSS File

2020-04-29 16:25 UTC, arps18 requested changes

2020-04-29 16:25 UTC, arps18 commented on navbar/index.html
> +<style>
![Screenshot (33)](https://user-images.githubusercontent.com/47818179/80618421-fd563400-8a60-11ea-8828-c1205ee5478b.png)

Kindly resolve the same!

2020-05-01 15:15 UTC, AyushBherwani1998 commented
Hey @Yagna24, thanks for contribution, any updates on the requested changes?

2020-05-01 15:26 UTC, Yagna24 commented
> Hey @Yagna24, thanks for contribution, any updates on the requested changes?

Updated the files , setting up mobile view for the same atm.

2020-05-01 15:55 UTC, AyushBherwani1998 commented
@Yagna24 thanks for the quick updates on the PR. Can you please attach the a screenshot for mobile view and desktop view?

2020-05-01 16:22 UTC, Yagna24 commented
> 
> 
> @Yagna24 thanks for the quick updates on the PR. Can you please attach a screenshot for mobile view and desktop view?

Yeah , sure 
![Screenshot (7)](https://user-images.githubusercontent.com/53996715/80821143-d54c0980-8bf5-11ea-84d0-6a367912ec44.png)
![Screenshot (8)](https://user-images.githubusercontent.com/53996715/80821148-d846fa00-8bf5-11ea-895e-392c302772bd.png)

2020-05-01 17:17 UTC, arps18 commented
> > @Yagna24 thanks for the quick updates on the PR. Can you please attach a screenshot for mobile view and desktop view?
> 
> Yeah , sure
> ![Screenshot (7)](https://user-images.githubusercontent.com/53996715/80821143-d54c0980-8bf5-11ea-84d0-6a367912ec44.png)
> ![Screenshot (8)](https://user-images.githubusercontent.com/53996715/80821148-d846fa00-8bf5-11ea-895e-392c302772bd.png)

- Kindly Work on the font section as well and try the same in the current index.html file on the repo!

2020-06-17 06:33 UTC, closed without merging